spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mikydemewoz/Library-system.git
#  profiles:
#    active: native
  application:
    name: Config-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 8888
